# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2018-05-24 16:24
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('jobapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('category', models.CharField(choices=[('TR', 'Travaux de renovations'), ('DM', 'Déménagement et manutention'), ('NR', 'Nettoyage et repassage'), ('CL', 'Conciergerie et gestion locative'), ('BA', 'Babysitter et accompagnatrice'), ('LV', 'Location de voiture'), ('IM', 'Reparation informatique et autre')], max_length=2)),
                ('description', models.CharField(max_length=1000)),
                ('price', models.IntegerField(default=10)),
                ('photo', models.FileField(upload_to='jobs')),
                ('status', models.BooleanField(default=True)),
                ('create_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
