# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2018-05-25 02:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobapp', '0002_job'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='slogan',
            field=models.CharField(default='Mon slogan', max_length=500),
            preserve_default=False,
        ),
    ]
